core = 7.x
api = 2
projects[drupal][version] = "7.34"

; Contrib Modules
projects[ctools][version] = "1.6"
projects[date][version] = "2.8"
projects[email][version] = "1.3"
projects[entity][version] = "1.5"
projects[entityreference][version] = "1.1"
projects[field_collection][version] = "1.0-beta8"
projects[field_group][version] = "1.4"
projects[libraries][version] = "2.2"
projects[link][version] = "1.3"
projects[pathauto][version] = "1.2"
projects[token][version] = "1.5"
projects[views][version] = "3.10"

; Themes
projects[open_framework][download][type] = "git"
projects[open_framework][download][url] = "git://github.com/SU-SWS/open_framework.git"
projects[open_framework][type] = "theme"
projects[open_framework][download][branch] = "7.x-2.x-dev"

; Libraries
libraries[jquery-ui-timepicker][download][type] = "file"
libraries[jquery-ui-timepicker][download][url] = "https://github.com/unb-libraries/drupal_patches/blob/master/digitalscholarship.lib.unb.ca/jquery-ui-timepicker.zip?raw=true"
libraries[jquery-ui-timepicker][directory_name] = "jquery-ui-timepicker"
libraries[jquery-ui-timepicker][type] = "library"
